# Generated by SMOLA v0.1.0 from examples/counter.smola
# Do not edit -- regenerate from the .smola source.

# Example: a non-leaf function that uses callee-saved registers.
# This exercises VAR.S, the frame planner, and a CALL through which
# values must survive.

    # smola: struct Counter (16 bytes, align 8)
    .set Counter_value_offset, 0
    .set Counter_increment_offset, 8
    .set Counter_size, 16
    .set Counter_align, 8






    .section .text.counter_advance_n, "ax", @progbits
    .globl  counter_advance_n
    .type   counter_advance_n, @function
    .balign 2
counter_advance_n:
    addi sp, sp, -16    # smola: prologue, frame=16
    sd   s0, 0(sp)              # smola: save s0
    sd   s1, 8(sp)              # smola: save s1
# Signature: counter_advance_n(Counter *self, i64 n)
#   advances self->value by self->increment, n times.
# Returns: the final value in a0.
    # smola: bind counter -> a0  (argument)
    # smola: bind n -> a1  (argument)

# We need 'counter' and 'n' to survive across a (hypothetical)
# call to a logging function, so move them into callee-saved regs.
    # smola: bind c_save -> s0  (callee-saved, frame slot reserved)
    # smola: bind n_save -> s1  (callee-saved, frame slot reserved)
    mv   s0, a0    # MV c_save, counter
    mv   s1, a1    # MV n_save, n

    # smola: bind inc -> t0  (caller-saved)
    ld   t0, 8(s0)    # LOAD_FIELD inc, c_save, Counter.increment

# Loop n_save times.
    # smola: bind val -> t1  (caller-saved)
    ld   t1, 0(s0)    # LOAD_FIELD val, c_save, Counter.value

.Lloop:
    beqz s1, .Ldone    # BEQZ n_save, .Ldone
    add  t1, t1, t0    # ADD val, val, inc
    addi s1, s1, -1    # ADDI n_save, n_save, -1
    j    .Lloop    # J .Lloop

.Ldone:
    sd   t1, 0(s0)    # STORE_FIELD val, c_save, Counter.value
    mv   a0, t1    # MV a0, val
    # smola: free val
    # smola: free inc
    ld   s1, 8(sp)              # smola: restore s1
    ld   s0, 0(sp)              # smola: restore s0
    addi sp, sp, 16     # smola: epilogue
    ret
    .size counter_advance_n, .-counter_advance_n

