# Generated by SMOLA v0.1.0 from examples/insn_length.smola
# Do not edit -- regenerate from the .smola source.

# Example: a smold-style instruction-length detection helper.
# Mirrors the M1 smold_insn_length function from the smold design doc.


    .section .text.detect_insn_length, "ax", @progbits
    .globl  detect_insn_length
    .type   detect_insn_length, @function
    .balign 2
detect_insn_length:
# Input:  a0 = first halfword of the instruction
# Output: a0 = 2 if compressed, 4 if standard 32-bit,
#                or sets a1 != 0 to signal unsupported length.
#
# Encoding rules (RISC-V manual section 1.5):
#   bits[1:0] != 11      -> 16-bit compressed
#   bits[1:0] == 11 and
#     bits[4:2] != 111   -> 32-bit standard
#   otherwise            -> 48-bit+ (unsupported here)

    # smola: bind insn -> a0  (argument)
    # smola: bind unsupported -> a1  (argument)
    # smola: bind low2 -> t0  (caller-saved)
    # smola: bind low5 -> t1  (caller-saved)

# Default: not unsupported.
    li   a1, 0    # LI unsupported, 0

# Check low two bits.
    andi t0, a0, 3    # ANDI low2, insn, 3
    li   t1, 3    # LI low5, 3
    bne  t0, t1, .Lcompressed    # BNE low2, low5, .Lcompressed

# 32-bit candidate: check bits[4:2].
    andi t1, a0, 0x1c    # ANDI low5, insn, 0x1c
    li   t0, 0x1c    # LI low2, 0x1c
    beq  t1, t0, .Llong    # BEQ low5, low2, .Llong

# 32-bit standard.
    li   a0, 4    # LI a0, 4
    j    .Lreturn    # J .Lreturn

.Lcompressed:
    li   a0, 2    # LI a0, 2
    j    .Lreturn    # J .Lreturn

.Llong:
    li   a1, 1    # LI unsupported, 1
    li   a0, 0    # LI a0, 0

.Lreturn:
    # smola: free low2
    # smola: free low5
    ret                          # smola: leaf epilogue
    .size detect_insn_length, .-detect_insn_length

