# Generated by SMOLA v0.1.0 from examples/point.smola
# Do not edit -- regenerate from the .smola source.

# Worked example: Point.translate from the spec.
# Demonstrates struct declaration, method definition, field access.

    # smola: struct Point (16 bytes, align 8)
    .set Point_x_offset, 0
    .set Point_y_offset, 8
    .set Point_size, 16
    .set Point_align, 8






    .section .text.Point_translate, "ax", @progbits
    .globl  Point_translate
    .type   Point_translate, @function
    .balign 2
Point_translate:
    # smola: bind self -> a0  (argument, implicit)
    # smola: bind dx -> a1  (argument)
    # smola: bind dy -> a2  (argument)
    # smola: bind cx -> t0  (caller-saved)
    # smola: bind cy -> t1  (caller-saved)

    ld   t0, 0(a0)    # LOAD_FIELD cx, self, Point.x
    ld   t1, 8(a0)    # LOAD_FIELD cy, self, Point.y
    add  t0, t0, a1    # ADD cx, cx, dx
    add  t1, t1, a2    # ADD cy, cy, dy
    sd   t0, 0(a0)    # STORE_FIELD cx, self, Point.x
    sd   t1, 8(a0)    # STORE_FIELD cy, self, Point.y
    ret                          # smola: leaf epilogue
    .size Point_translate, .-Point_translate

